"""phase 3: documents

Revision ID: 31c50429804f
Revises: d235f9a142c2
Create Date: 2026-09-12 13:38:04.548435
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31c50429804f'
down_revision: Union[str, None] = 'd235f9a142c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='document_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'content_hash', name='uq_document_org_content_hash'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_documents_org_status', 'documents', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_status', table_name='documents')
    op.drop_table('documents')
    # See the Phase 2 migration for why this is required: Alembic autogenerate
    # does not track the Postgres ENUM type's lifecycle independently of the
    # table that uses it.
    sa.Enum(name='document_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
